# This workflow will build a Java project with Maven and build and push docker image to Docker Hub


name: Build and Push docker image to Docker Hub
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build package
      run: mvn --batch-mode package --file pom.xml
    #  env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    #- name: Create artifacts directory and copy war file
     # run: mkdir artifacts && cp target/*.war artifacts
      
    - name: upload the artifact
      uses: actions/upload-artifact@v2
      with:
        
        path: ./webapp
        
   # - name: Create artifacts directory and copy war file
    #  run: mkdir artifacts && cp target/*.war artifacts


  Publish:
     needs: Build
     runs-on: self-hosted
     steps: 
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v1
       with:
         java-version: '11' 

     - name: Update version
       run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false
     - name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     
     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Download artifact
       uses: actions/download-artifact@v2

     #- name: Build and push
      # id: docker_build
       #uses: docker/build-push-action@v2
       #with:
        # context: .
         #push: true
         #tags: myimage
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag my-image-name 
